### ISSUE TITLE
[ALTO] Facturas

### ISSUE THREAD

**Issue by tomasmoreira04** [Shumaister/FrbaHotel#10]
Acá está lo que tira el debug mati

![image](https://user-images.githubusercontent.com/26699333/42131250-7715f9ca-7cd4-11e8-836c-8ed5158cf40b.png)

En la sección de código:
![image](https://user-images.githubusercontent.com/26699333/42131255-8b6862e6-7cd4-11e8-8ee2-59ca7bf52f89.png)
(all inclusive)

**Comment by MatiasVillanueva97** [comment]
Rrady
