### ISSUE TITLE
[BAJO] abm usuarios - rebuscandomeeeeeeee

### ISSUE THREAD

**Issue by tomasmoreira04** [Shumaister/FrbaHotel#13]
El admin puede eliminarse a si mismo, por lo que el sistema queda sin admin 😢  (a menos que se reactive por base)

**Comment by tomasmoreira04** [comment]
esto lo subo exclusivamente por el tema de que dijeron que joden con esas cosas chiquitas, por mi, chau

**Comment by DPoma** [comment]
Listo ahora ya no puede eliminarse a si mismo
