### ISSUE TITLE
[ALTO] Reservas clientes

### ISSUE THREAD

**Issue by tomasmoreira04** [Shumaister/FrbaHotel#16]
Un cliente deshabilitado puede hacer reservas.

Según el funcional:
Un cliente inhabilitado no podrá realizar reservas en ningún hotel de la cadena bajo ninguna circunstancia.

**Comment by Shumaister** [comment]
Aniadi a la consulta que pregunte por el estado del cliente, si esta en 1 esta habilitado, sino no
