### ISSUE TITLE
[ALTO] Hoteles - Reservas

### ISSUE THREAD

**Issue by tomasmoreira04** [Shumaister/FrbaHotel#17]
Se puede realizar una reserva en un hotel que está cerrado.

Funcional:
Durante ese período se podrán tomar reservas para fechas futuras y las mismas no podrán incluir ningún día donde el hotel se esté remodelando

**Comment by Shumaister** [comment]
DIOS NOS AYUDE

**Comment by Shumaister** [comment]
ahi valido que el hotel este en estado 1
