### ISSUE TITLE
[MEDIO] Sobre el issue anterior

### ISSUE THREAD

**Issue by tomasmoreira04** [Shumaister/FrbaHotel#19]
Si no le das bola a lo que te dice el programa y apretas en confirmar cancelación, el sistema se rompe:
![image](https://user-images.githubusercontent.com/26699333/42194183-250ecbc2-7e49-11e8-994c-a2b39deb5245.png)

**Valores del debug**
![image](https://user-images.githubusercontent.com/26699333/42194209-3c8bd8da-7e49-11e8-96a9-6acf771e26b2.png)

**En la sección de código**
![image](https://user-images.githubusercontent.com/26699333/42194225-4a76223e-7e49-11e8-94a1-e0cf1f116e10.png)

**Comment by Shumaister** [comment]
puse try y catch para agarrar estas forradas inconsistentes
