### ISSUE TITLE
[BAJO] ABM Hoteles - Fecha creaci´no

### ISSUE THREAD

**Issue by tomasmoreira04** [Shumaister/FrbaHotel#21]
Por defecto se pone la fecha 1/1/0001.
Si apretas en guardar, salta:
![image](https://user-images.githubusercontent.com/26699333/42194787-0882dcc0-7e4c-11e8-8b7c-62102a4d153c.png)

Y si luego de esto, ignoramos el cartelito ese, cerrandolo, nos dice que el hotel se modificó, aunque obviamente no lo hace

**Comment by DPoma** [comment]
Necesito mas detalles de cuando pasa esto

**Comment by tomasmoreira04** [comment]
Pomita, creo que esto era cuando modificas un hotel

**Comment by Shumaister** [comment]
dat testet
