### ISSUE TITLE
[MUY ALTO] Reservas con misma habitación

### ISSUE THREAD

**Issue by tomasmoreira04** [Shumaister/FrbaHotel#22]
Actualmente se están generando reservas para la misma habitación si se le pasan los mismos parámetros. Es decir, que no se está validando que las habitaciones no estén disponibles para su reserva.
![image](https://user-images.githubusercontent.com/26699333/42195170-fc461f88-7e4d-11e8-9b56-50bdafae8039.png)

**Comment by Shumaister** [comment]
Ya se bloquea el boton

**Comment by Shumaister** [comment]
ya no mas, en teoria ya no te trae la misma hab
