### ISSUE TITLE
Tablas que hay que conectar.

### ISSUE THREAD

**Issue by tomasmoreira04** [Shumaister/FrbaHotel#3]
Solo para recordarlo, después del commit de Mati quedaron estas tablas sin relacionarse:

*TipoDocumento --> debería relacionarse con Personas
*Huespedes --> debería relacionarse con Clientes y con Estadia
*Reserva_Estado --> debería relacionarse con Reserva
*Consumidos --> debería relacionarse con Estadia, Reserva y Consumible
*Consumibles --> se relacionaba con itemfactura antes, ahora ¿debería relacionarse con consumidos?

Además falta una FK desde estadía a reserva (o la inversa)
Con esto dicho: no sería mejor que en la tabla de consumidos haya una sola FK a reserva o a estadia (ahora hay fk a ambas)? Ya que se supone, están relacionadas

Si encuentro más las agrego

**Comment by DPoma** [comment]
Ya esta todo relacionado y agregue algunas tablas faltantes, salu2
