### ISSUE TITLE
[BAJO] Falta una validación en la selección del hotel

### ISSUE THREAD

**Issue by tomasmoreira04** [Shumaister/FrbaHotel#4]
Después de loguearse, está el ComboBox de selección de hotel.

Si uno, en vez de seleccionar el hotel desde el selector, escribe un hotel incorrecto y aprieta en Ingresar, se despliega el siguiente error no manejado:

![image](https://user-images.githubusercontent.com/26699333/42120793-c8298742-7bf7-11e8-8627-cbde9ececd1d.png)

(estoy debuggeando)

**Comment by DPoma** [comment]
Cierto, nunca se me hubiera ocurrido, si es fácil de corregir lo arreglamos sino se deja así como esta (quiero creer que no van a ser tan forros en la corrección)

**Comment by DPoma** [comment]
Este bug marco un antes y un despues ahora los comboBox se ven mas decentes, se solucionaba haciendo esto:
**_MiComboBox.DropDownStyle = ComboBoxStyle.DropDownList;_**
