### ISSUE TITLE
[BASE] Tabla Huespedes

### ISSUE THREAD

**Issue by tomasmoreira04** [Shumaister/FrbaHotel#5]
Hay que decidir si dejar o fletar esta tabla, ya que en el DER está colgada.

Pomita me había dicho que no la usó porque no sabía donde carajo meterla.

**Comment by DPoma** [comment]
La tabla huespedes ya tiene las FK's correspondientes basicamente es la tabla intermedia de un muchos a muchos entre clientes y estadias, tambien ahora la tabla Estadias_Habitaciones paso a ser Reservas_Habitaciones por cuestiones de simplicidad.

**Comment by tomasmoreira04** [comment]
Buenísimo Pomita, ahora le doy una mirada mientras testeo y hago el DER
