### ISSUE TITLE
[ALTO] Roles - Ingresar con Rol desactivado

### ISSUE THREAD

**Issue by tomasmoreira04** [Shumaister/FrbaHotel#6]
Según el funcional:
"En el supuesto caso que un usuario tenga asignado un rol inhabilitado, el mismo no puede ser seleccionado al momento del login." página 6

Sin embargo, si uno da de alta un usuario, y le asigna un rol inhabilitado, puede loguearse, seleccionar el rol inhabilitado, y usar las funcionalidades como si estuviera habilitado

**Comment by Shumaister** [comment]
@MatiasVillanueva97 miralo vos, este bastante sencillo

**Comment by DPoma** [comment]
Ya esta hecho
