### ISSUE TITLE
[BAJO] Copypasteo en campos

### ISSUE THREAD

**Issue by tomasmoreira04** [Shumaister/FrbaHotel#7]
Solo a modo comentario. Se que es una forreada esta prueba, pero me dijeron que lo haga mierda jajaja.

Si bien al hacer inputs manuales restrictivos, como por ejemplo en los campos para los nombres de usuarios, roles, etc etc., que (por ejemplo) solo aceptan letras, si desde otro lado pones números en el clipboard y los pegas en el input, se puede poner tranquilamente números a un nombre.

Es algo muy bobo y rebuscado, pero lo pongo por si las dudas =P

**Comment by DPoma** [comment]
En un universo paralelo seguramente vamos a validar ese error, salu2

**Comment by DPoma** [comment]
Ni puta idea como se valida eso, cierro
