### ISSUE TITLE
[ALTO] Creación de usuarios

### ISSUE THREAD

**Issue by tomasmoreira04** [Shumaister/FrbaHotel#8]
Tengo una ligera duda.

Un usuario administrador: ¿puede dar de alta usuarios que no sean de los hoteles que tiene asignados?

**Comment by DPoma** [comment]
Si, lo dice en la pagina 7 del enunciado:

_"Debe tenerse en cuenta que el password se pueda modificar una vez que el usuario se
encuentre logueado, **también debe contemplarse que un administrador solo puede realizar
modificaciones y dar de baja a usuarios que se desempeñen en el mismo hotel él trabaja**"_

Por lo tanto solo hay que tener en cuenta esa restricción para modificaciones y bajas

**Comment by tomasmoreira04** [comment]
Ahora lo vuelvo a revisar, pero me parece que eso no estaba validado

**Comment by tomasmoreira04** [comment]
Confirmo el bug, siendo administrador de otro hotel, puedo agregar usuario a un hotel sobre el que no tengo permiso

**Comment by Shumaister** [comment]
Por lo que entendimos con poma, solo de valida si es del mismo hotel para la modificacion y baja de los usuarios. 

Se cierra
