### ISSUE TITLE
[MEDIO] Bug al cerrar ventana de reserva

### ISSUE THREAD

**Issue by tomasmoreira04** [Shumaister/FrbaHotel#9]
Tuve un problemita al cerrar la ventana de una reserva cuando el usuario es nuevo.

Pasos:
Correr la aplicación, click en Cliente.
Mis reservas -> Nueva reserva.

Completar todos los pasos hasta llegar al 3.
Aquí, clickear en Soy nuevo. Cerrar la ventana que se abre, y la app se rompe.

Al debuggear, el visual dice que rompe en esta region:
![image](https://user-images.githubusercontent.com/26699333/42131147-5ac76964-7cd1-11e8-9053-a2862f7fa14e.png)

**Comment by Shumaister** [comment]
Eso sucede porque si o si te pide que ingreses un usuario, ahi veo como lo manejo para que no estalle

**Comment by Shumaister** [comment]
Excelente bug, bien testeado eso! 

Ahi lo solucione bastate . Lo que hice bien sencillo es poner un try un catch, si falla te mando un popup con una alerta que te dice que es obligatorio que pongas al cliente.

Arrelado.
